table dim_date
	lineageTag: de9ce3c2-b580-49e0-817a-5b94a1908ecd

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: a5bf5051-d96a-4d1a-8436-25e4a579eef6
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 251b1c12-9756-4e37-9b40-ac6c449289fc
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 94f9c8ee-302d-43af-bd1e-d587000c326b
			defaultHierarchy: LocalDateTable_49545699-a821-4e20-bf0e-8a59aa1d0102.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5b0380ac-1c22-4efe-a424-feb33c86c30b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: b2aa42fa-8ff2-48dd-abaf-c12176b4d31f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 306ab140-5104-4a73-8138-c52a794c6b2f
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: 0b40a96f-29a3-4518-a134-992e46986439
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d6566405-fda9-48dc-a281-68d9934f8f51
		summarizeBy: none
		sourceColumn: Year Month

		variation Variation
			isDefault
			relationship: cfc9f305-1a18-42b8-985d-93fbee8c293d
			defaultHierarchy: LocalDateTable_f73ad784-8138-442b-b8f2-c56f50e8a29f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: string
		lineageTag: 308afd01-ce73-4d7b-8dd3-96f8676898c0
		summarizeBy: none
		sourceColumn: Fiscal Year
		sortByColumn: 'Fiscal Year Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Sort'
		dataType: int64
		formatString: 0
		lineageTag: e141b672-8745-4eea-bda4-982cbe45e8ea
		summarizeBy: none
		sourceColumn: Fiscal Year Sort

		annotation SummarizationSetBy = User

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 7e117523-a00f-4712-80c0-371196ccf68f
		summarizeBy: none
		sourceColumn: Fiscal Quarter
		sortByColumn: 'Fiscal Quarter Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Sort'
		dataType: int64
		formatString: 0
		lineageTag: 66a16fb7-9d5b-43c1-8f89-b4553e8ed884
		summarizeBy: none
		sourceColumn: Fiscal Quarter Sort

		annotation SummarizationSetBy = User

	column 'Fiscal Period'
		dataType: int64
		formatString: 0
		lineageTag: 9b59f47a-01ec-4663-bb0d-b21fce764394
		summarizeBy: none
		sourceColumn: Fiscal Period

		annotation SummarizationSetBy = User

	column 'Fiscal Period Name'
		dataType: string
		lineageTag: ebe9bd2f-6d22-406c-8e9a-3f79676b0d97
		summarizeBy: none
		sourceColumn: Fiscal Period Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Period Caption'
		dataType: string
		lineageTag: f0ffa507-fa80-4b63-b0ed-426710c43f6e
		summarizeBy: none
		sourceColumn: Fiscal Period Caption

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Caption'
		dataType: string
		lineageTag: 8a9ae8b6-0e69-4131-be71-0e0fd4515f0b
		summarizeBy: none
		sourceColumn: Fiscal Quarter Caption
		sortByColumn: 'Fiscal Quarter Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Period Sort'
		dataType: int64
		formatString: 0
		lineageTag: c8d2b414-3ce5-4d8e-870b-3f434cfe7589
		summarizeBy: none
		sourceColumn: Fiscal Year Period Sort

		annotation SummarizationSetBy = User

	column 'Weeks In Period'
		dataType: int64
		formatString: 0
		lineageTag: eda8e341-d677-41c5-9696-f0f51a32a2c0
		summarizeBy: sum
		sourceColumn: Weeks In Period

		annotation SummarizationSetBy = Automatic

	column 'Weeks In Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 3d7d40c0-3be4-43af-b36c-ef9820db8c7c
		summarizeBy: sum
		sourceColumn: Weeks In Quarter

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PlanningSample\dim_date.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year Month", type date}, {"Fiscal Year", type text}, {"Fiscal Year Sort", Int64.Type}, {"Fiscal Quarter", type text}, {"Fiscal Quarter Sort", Int64.Type}, {"Fiscal Period", Int64.Type}, {"Fiscal Period Name", type text}, {"Fiscal Period Caption", type text}, {"Fiscal Quarter Caption", type text}, {"Fiscal Year Period Sort", Int64.Type}, {"Weeks In Period", Int64.Type}, {"Weeks In Quarter", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

