table dim_region
	lineageTag: f2e87ddb-15d9-453f-b8c2-adccac105180

	column RegionKey
		dataType: int64
		formatString: 0
		lineageTag: bc038aa6-c990-4ba0-a88b-74152145435f
		summarizeBy: none
		sourceColumn: RegionKey

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: a7a2f468-d51e-48ba-a58b-29a36768daef
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	partition dim_region = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PlanningSample\dim_region.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RegionKey", Int64.Type}, {"RegionName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

