table dim_category
	lineageTag: 16f712d1-b290-4298-b68d-dd3639e9b280

	column CategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 8018b3f4-a89d-4afe-9902-a55fc1f83fc9
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 63508c73-2c1b-4fed-a3e0-48ee7a747717
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition dim_category = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PlanningSample\dim_category.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

