#!/usr/bin/env python3
"""Where every drift-audit brief stands, as a README.md in its directory.

    uv run scripts/audit-status.py                     # regenerate every index
    uv run scripts/audit-status.py --dir docs/audits/2026-09-12/skills-for-fabric
    uv run scripts/audit-status.py --check             # stale or missing? pre-commit

Each docs/audits/<date>/<source>/ directory gets one generated README.md:
a table with a row per brief giving the actions it covers, its Kind, and
its status. GitHub renders it when the directory is browsed, which is the
point -- before this existed the only way to learn which of eleven briefs
had been executed was to open eleven files.

Nothing in the index is hand-maintained. Status is DERIVED from what each
brief already carries: the metadata block /drift-handoff writes, and the
`## Execution log` that /drift-update appends. A hand-kept status column
would be a third copy of a fact that already lives in the log, and this
repo has lost enough counts to that pattern to know how it ends. So the
table is regenerated, never edited: /drift-handoff runs this after
writing a directory, /drift-update runs it after every stamp, and the
pre-commit hook runs --check so a forgotten regeneration fails instead of
rotting.

What the rows read, from each brief:

  Actions   the `**Covers recommended actions**:` metadata line, minus
            any parenthetical long enough to be prose
  Kind      the `**Kind**:` line, cut at its first clause boundary -- the
            distinction /drift-update triages on (edit, decision,
            investigation) is in those first words by convention
  Status    pending           no `## Execution log` yet
            <outcome> <date>  the `**Executed**:` line's date and leading
                              outcome word or phrase -- applied, applied
                              with deferrals, already-applied, escalated,
                              deferred -- with the rest of the line dropped
            closed <date>     appended when the log also carries a
                              `**Closed**:` line, the key a later session
                              adds when a deferral or an escalation is
                              discharged. Without it an escalated brief
                              reads as open forever, which is how the four
                              /author-skill runs that settled
                              2026-09-10/skills-for-fabric/07 left no
                              trace in the ledger.

An escalated row that is not closed links to the audit follow-up table in
docs/handoffs/execute/README.md, which is where the work its answer
implies is queued. The index says what state a brief is in; the queue says
what its outstanding work needs. Neither restates the other.

Parsing is deliberately strict about shape and loose about words: a
brief with an `## Execution log` but no `**Executed**:` line, or one whose
Executed line has no date, is reported as `unparsed` so it is visible in
the table rather than silently pending. Only stdlib is used, so the
pre-commit hook needs no extra dependency.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
AUDITS = REPO / "docs" / "audits"
QUEUE = "handoffs/execute/README.md"  # relative to docs/
QUEUE_ANCHOR = "audit-briefs-are-a-second-queue"

# 00-audit-report.md, and 00b-audit-report-rerun.md when a source was
# audited twice in one day and the second report was kept beside the first.
REPORT_RE = re.compile(r"^00[a-z]?-audit-report.*\.md$")
BRIEF_RE = re.compile(r"^(\d{2})-(?!audit-report).+\.md$")
META_RE = re.compile(r"^- \*\*([^*]+)\*\*:\s*(.*)$")
EXECUTED_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})\s*(?:[—–-]+\s*)?(.*)$")
# Longest first, so "applied with deferrals" wins over "applied".
OUTCOMES = ("applied with deferrals", "already-applied", "escalated", "deferred", "applied")

BANNER = (
    "<!-- Generated by scripts/audit-status.py from the briefs in this directory.\n"
    "     Do not edit by hand: re-run the script, or let /drift-update do it. -->\n"
)


def audit_dirs() -> list[Path]:
    """Every <date>/<source> directory that holds an audit report."""
    found = []
    if not AUDITS.is_dir():
        return found
    for date_dir in sorted(AUDITS.iterdir()):
        if not date_dir.is_dir():
            continue
        for src_dir in sorted(date_dir.iterdir()):
            if src_dir.is_dir() and any(REPORT_RE.match(p.name) for p in src_dir.iterdir()):
                found.append(src_dir)
    return found


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def metadata(lines: list[str]) -> dict[str, str]:
    """The `- **Key**: value` block under the H1, continuation lines joined."""
    meta: dict[str, str] = {}
    key = None
    for line in lines:
        if line.startswith("## "):
            break
        m = META_RE.match(line)
        if m:
            key = m.group(1).strip()
            meta[key] = m.group(2).strip()
        elif key and line.startswith("  ") and line.strip():
            meta[key] += " " + line.strip()
        elif not line.strip():
            key = None
    return meta


def execution_log(lines: list[str]) -> dict[str, str] | None:
    """The `- **Key**: value` entries under `## Execution log`, or None."""
    try:
        start = lines.index("## Execution log")
    except ValueError:
        return None
    log: dict[str, str] = {}
    key = None
    for line in lines[start + 1 :]:
        if line.startswith("## "):
            break
        m = META_RE.match(line)
        if m:
            key = m.group(1).strip()
            log[key] = m.group(2).strip()  # a repeated key keeps its last value
        elif key and line.startswith("  ") and line.strip():
            log[key] += " " + line.strip()
        elif not line.strip():
            key = None
    return log


def strip_md(text: str) -> str:
    return text.replace("**", "").strip()


def kind_summary(kind: str) -> str:
    """The Kind line up to its first clause boundary, bold stripped."""
    text = strip_md(kind)
    cut = len(text)
    for sep in (". ", " — ", " -- ", "; ", ": "):
        i = text.find(sep)
        if 0 < i < cut:
            cut = i
    text = text[:cut].rstrip(".")
    if len(text) > 90:
        text = text[:89].rsplit(" ", 1)[0] + "…"
    return text


def outcome_of(executed: str) -> tuple[str, str] | None:
    """(date, outcome) from an Executed line, or None when it has no date."""
    m = EXECUTED_RE.match(strip_md(executed))
    if not m:
        return None
    date, rest = m.group(1), m.group(2).strip().lower()
    for word in OUTCOMES:
        if rest.startswith(word):
            return date, word
    # An outcome this script does not know: keep its first words rather
    # than hide it, so the table shows what the log actually says.
    head = re.split(r"[(;,.]", rest, maxsplit=1)[0].strip()
    return date, (head or "unlabelled")


def actions_summary(actions: str) -> str:
    """The Covers line, minus any parenthetical long enough to be prose."""
    return re.sub(r"\s*\([^)]{30,}\)", "", strip_md(actions)).strip()


def status_cell(log: dict[str, str] | None, rel_queue: str) -> tuple[str, str]:
    """(table cell, tally key) for one brief's execution log."""
    if log is None:
        return "pending", "pending"
    executed = log.get("Executed")
    if not executed:
        return "unparsed — `## Execution log` has no `**Executed**:` line", "unparsed"
    parsed = outcome_of(executed)
    if parsed is None:
        return "unparsed — `**Executed**:` line carries no date", "unparsed"
    date, outcome = parsed
    cell = f"{outcome} {date}"
    closed = log.get("Closed")
    if closed:
        cm = EXECUTED_RE.match(strip_md(closed))
        cell += f" · closed {cm.group(1)}" if cm else " · closed (undated)"
        return cell, "closed"
    if outcome == "escalated":
        cell += f" · [queue]({rel_queue}#{QUEUE_ANCHOR})"
    return cell, outcome


def render(src_dir: Path) -> str:
    date, source = src_dir.parent.name, src_dir.name
    # Up to docs/, then down: docs/audits/<date>/<source>/ is three below it.
    depth = len(src_dir.relative_to(REPO / "docs").parts)
    rel_queue = "../" * depth + QUEUE
    reports = sorted(p.name for p in src_dir.iterdir() if REPORT_RE.match(p.name))
    briefs = sorted(p for p in src_dir.iterdir() if BRIEF_RE.match(p.name))

    rows = []
    tally: dict[str, int] = {}
    for brief in briefs:
        lines = read_text(brief).split("\n")
        title = next((ln[2:] for ln in lines if ln.startswith("# ")), brief.stem)
        title = re.sub(r"^Handoff:\s*", "", title)
        meta = metadata(lines)
        number = BRIEF_RE.match(brief.name).group(1)
        actions = actions_summary(meta.get("Covers recommended actions", "?"))
        kind = kind_summary(meta.get("Kind", "?"))
        status, head = status_cell(execution_log(lines), rel_queue)
        tally[head] = tally.get(head, 0) + 1
        rows.append(f"| [{number} {title}]({brief.name}) | {actions} | {kind} | {status} |")

    report_links = ", ".join(f"[{r}]({r})" for r in reports)
    summary = " · ".join(f"{k} {v}" for k, v in sorted(tally.items()))
    out = [
        BANNER,
        f"# Audit index — {source}, {date}",
        "",
        f"Report: {report_links}",
        "",
        f"Briefs: {len(briefs)}" + (f" — {summary}" if summary else ""),
        "",
        "| Brief | Actions | Kind | Status |",
        "| --- | --- | --- | --- |",
        *rows,
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", action="append", type=Path, help="one audit directory; repeatable")
    ap.add_argument("--check", action="store_true", help="fail if any README.md is missing or stale")
    args = ap.parse_args()

    dirs = [d.resolve() for d in args.dir] if args.dir else audit_dirs()
    if not dirs:
        print("no audit directories under docs/audits/")
        return 0

    stale = []
    for src_dir in dirs:
        if not src_dir.is_dir():
            print(f"not a directory: {src_dir}", file=sys.stderr)
            return 2
        target = src_dir / "README.md"
        wanted = render(src_dir)
        current = read_text(target) if target.exists() else None
        rel = target.relative_to(REPO).as_posix()
        if args.check:
            if current != wanted:
                stale.append(rel)
        elif current != wanted:
            target.write_text(wanted, encoding="utf-8", newline="\n")
            print(f"wrote {rel}")
        else:
            print(f"current {rel}")

    if args.check and stale:
        for rel in stale:
            print(f"stale or missing: {rel}")
        print("regenerate with: uv run scripts/audit-status.py")
        return 1
    if args.check:
        print(f"{len(dirs)} audit index(es) current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
